|       |     |                                                                       |
| gen00 | 20% | try to use xgen to generate go code from xsd file, not working so far |
| gen01 |     | try reading kml with https://github.com/amundsentech/kml-decode       |
|       |     |                                                                       |

* Synopsis

I want to open KML files with satellite acquisition plans
[SATPLAN]. This is how ESA distributes information the footprints on
earth where the Sentinel-1 satellites will acquire data in a period of
20 days.

KML is a file format based on XML. The XSD definition file is
published at [XMLXSD].


* Generate Go code to parse XML using the xgen tool


#+begin_example
cd xsd
curl http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd -O
curl http://schemas.opengis.net/kml/2.2.0/atom-author-link.xsd -O
curl http://docs.oasis-open.org/election/external/xAL.xsd -O

curl https://sentinel.esa.int/documents/247904/4742706/S1A_MP_USER_20220715T160000_20220804T180000.kml -O
go install github.com/xuri/xgen/cmd/...@latest

~/go/bin/xgen -i xsd -o schema -l Go

#+end_example

* Contents of the KML file
#+begin_example
xmlstarlet el -u S1A*.kml

kml
kml/Document
kml/Document/Folder
kml/Document/Folder/Folder
kml/Document/Folder/Folder/Placemark
kml/Document/Folder/Folder/Placemark/ExtendedData
kml/Document/Folder/Folder/Placemark/ExtendedData/Data
kml/Document/Folder/Folder/Placemark/ExtendedData/Data/value
kml/Document/Folder/Folder/Placemark/LinearRing
kml/Document/Folder/Folder/Placemark/LinearRing/altitudeMode
kml/Document/Folder/Folder/Placemark/LinearRing/coordinates
kml/Document/Folder/Folder/Placemark/LinearRing/tessellate
kml/Document/Folder/Folder/Placemark/TimeSpan
kml/Document/Folder/Folder/Placemark/TimeSpan/begin
kml/Document/Folder/Folder/Placemark/TimeSpan/end
kml/Document/Folder/Folder/Placemark/name
kml/Document/Folder/Folder/Placemark/styleUrl
kml/Document/Folder/Folder/name
kml/Document/Folder/name
kml/Document/NetworkLink
kml/Document/NetworkLink/Link
kml/Document/NetworkLink/Link/href
kml/Document/NetworkLink/name
kml/Document/Style
kml/Document/Style/LineStyle
kml/Document/Style/LineStyle/color
kml/Document/Style/LineStyle/width
kml/Document/name
#+end_example

* Appendix
** godef for emacs go-mode
go get github.com/rogpeppe/godef

** Unrelated note on emacs with termux
I have issues with an external keyboard on the Phone. It is connected
via an USB OTG adapter. C-Space doesn't work in emacs that runs inside
a termux terminal window. This key combination performs the
set-mark-command and is important for copy and paste. For the fix
uncomment the last line (starting with ctrl-space...) in
~/.termux/termux.properties.

Note: This fix seems to work only works sometimes. If it is not
working just call M-x set-mark-command.

* References 

|           |                                                                                                     |
|-----------+-----------------------------------------------------------------------------------------------------|
| [GOXML]   | https://github.com/twpayne/go-kml                                                                   |
| [XMLXSD]  | http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd                                                                                                    |
| [SATPLAN] | https://sentinel.esa.int/web/sentinel/missions/sentinel-1/observation-scenario/acquisition-segments |
|           |                                                                                                     |
