# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_load_netcdf_tensor.ipynb.

# %% auto 0
__all__ = ['start_time', 'debug', 'parser', 'args', 'fn', 'xs']

# %% ../01_load_netcdf_tensor.ipynb 0
# |export
#|default_exp p01_load_netcdf_tensor


# %% ../01_load_netcdf_tensor.ipynb 1
import os
import time
import pathlib
import numpy as np
import pandas as pd
import xarray as xr
import argparse



# %% ../01_load_netcdf_tensor.ipynb 2
start_time=time.time()
debug=True
_code_git_version="f4a1c1babae0be5c2244254207ab54b1e4cb79c6"
_code_repository="https://github.com/plops/cl-py-generator/tree/master/example/33_netcdf_tensor/source/"
_code_generation_time="12:07:52 of Sunday, 2022-09-04 (GMT+1)"
start_time=time.time()
debug=True


# %% ../01_load_netcdf_tensor.ipynb 3
parser=argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="enable verbose output", action="store_true")
args=parser.parse_args()


# %% ../01_load_netcdf_tensor.ipynb 4
fn="/home/martin/stage/cl-golang-generator/examples/33_netcdf_tensor/source00/newdata.nc"
xs=xr.open_dataset(fn)
print(xs.val)

