name: CI
on:
  push:
    paths:
      - 'examples/34_bbolt/source00/*'
  workflow_dispatch:

defaults:
  run:
    working-directory: 'examples/34_bbolt/source00/'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -x

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: 'examples/34_bbolt/source00/main'
  